services:
  aria2-pro:
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=aria2
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - aria2-config:/config
      - aria2-downloads:/downloads
    networks:
      - nginx_network
    deploy:
      placement:
        constraints:
          - node.labels.htpc == true
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: json-file
      options:
        max-size: 1m
    extra_hosts:
      # alist 发送的文件接收不到，不知道为啥
      - alist.mamm.me:192.168.8.8

  ariang:
    image: p3terx/ariang
    command: --port 6880 --ipv6
    networks:
      - nginx_network
    deploy:
      placement:
        constraints:
          - node.labels.htpc == true
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: json-file
      options:
        max-size: 1m

volumes:
  aria2-config:
  aria2-downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nas/data/downloads
      o: bind

networks:
  nginx_network:
    external: true
    name: portainer_nginx_network